{
 "title": "downloads",
 "time": { "from": "now/y", "to": "now/y" },
 "panels": [
  {
   "title": "Downloads vs Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "tool" ], "type": "tag" }
     ],
     "measurement": "downloads",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"downloads\" WHERE $timeFilter GROUP BY time(1d), \"tool\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total downloads per Tool",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "tool" ], "type": "tag" }
     ],
     "measurement": "downloads",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"downloads\" WHERE $timeFilter GROUP BY time(1d), \"tool\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unique Users",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "username" ], "type": "tag" }
     ],
     "measurement": "downloads",
     "query": "SELECT SUM(mean) FROM (SELECT mean(\"count\") FROM \"autogen\".\"downloads\" WHERE $timeFilter GROUP BY \"username\")",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Usage Per User",
   "type": "table",
   "gridPos": { "h": 17, "w": 2, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "username" ], "type": "tag" }
     ],
     "measurement": "downloads",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Installation Log",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 2, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "username" ], "type": "tag" },
      { "params": [ "tool" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "artifactory" ], "type": "tag" },
      { "params": [ "downloader_ver" ], "type": "tag" }
     ],
     "measurement": "downloads",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total downloads per Artifactory",
   "type": "stat",
   "gridPos": { "h": 17, "w": 10, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "artifactory" ], "type": "tag" }
     ],
     "measurement": "downloads",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"downloads\" WHERE $timeFilter GROUP BY time(1d), \"tool\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 17, "w": 10, "x": 0, "y": 26 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "username" ], "type": "tag" },
      { "params": [ "tool" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" }
     ],
     "measurement": "downloads",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}