version: "3.0"
services:
  influxdb:
    image: "influxdb:1.8"
    restart: always
    ports:
      - "9977:8086"
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    volumes:
      - influxdb:/var/lib/influxdb

  grafana:
    build: grafana/.
    restart: always
    ports:
      - "3333:3000"
    volumes:
      - grafanadb:/var/lib/grafana

  python-sharepoint:
    build: sharepoint/.
    restart: always
    environment:
      # do not forget to set these envs on the host
      - client_id=${client_id}
      - client_secret=${client_secret}
    volumes:
      - ./settings:/settings

volumes:
  influxdb:
  grafanadb:

