version: "3.0"
services:
  influxdb:
    image: "influxdb:1.8"
    restart: always
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    volumes:
      - influxdb:/var/lib/influxdb

  grafana:
    build: grafana/.
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafanadb:/var/lib/grafana

  python-sharepoint:
    build: ../.
    restart: always
    environment:
      # do not forget to set these envs on the host
      - client_id
      - client_secret
    volumes:
      # create folder "settings" in the same dir with this file and put there downloader config files
      - ./settings:/settings

volumes:
  influxdb:
  grafanadb:

