trigger: none
pool:
  name: Ansys
steps:
- template: templates\cleaning_env.yml
- script: |
    @echo OFF
    echo "Current working directory is %CD%"
    echo "Create python virtual environment"
    mkdir py_venv
    py -3.7 -m pip install --user pipenv
    py -3.7 -m venv py_venv

    :: activate virtual environment only via .bat
    set act_bat=py_venv\Scripts\activate.bat
    if not exist %act_bat% (
        echo %act_bat% doesn't exist
        exit 2
    )
    call %act_bat%
    python -m pip install -r requirements.txt
    echo "Python dependencies are installed"
  displayName: 'Install Python Dependencies'

- script: |
    echo Start packaging Python
    call py_venv\Scripts\activate.bat
    cd electron_ui
    pyinstaller.exe ..\downloader_backend.py --distpath python_build --workpath %TEMP% --exclude-module tkinter --onefile --noconsole  --hidden-import plyer.platforms.win.notification
    Xcopy /E /I ..\notifications python_build\notifications
  displayName: 'Build Python Exe'

- script: |
    echo "Create py -3.7 dev virtual environment"
    mkdir py_venv_dev
    py -3.7 -m pip install --user pipenv
    py -3.7 -m venv py_venv_dev

    :: activate virtual environment only via .bat
    set act_bat=py_venv_dev\Scripts\activate.bat
    if not exist %act_bat% (
        echo %act_bat% doesn't exist
        exit 2
    )
    call %act_bat%
    python -m pip install -r requirements-dev.txt
    echo "Python dev dependencies are installed"
  displayName: 'Install Python Dev Dependencies'
- template: templates\run_tests.yml
- script: |
    pushd electron_ui
    echo "Current working directory is %CD%"
    npm install
    echo "Dependencies are installed"
    popd
  displayName: 'Install NodeJS Dependencies'

- script: |
    set GH_TOKEN=$(gh_token)
    pushd electron_ui
    npm run deploy
    popd
  displayName: 'Build and Deploy Electron App to GitHub'

- script: |
    call py_venv_dev\Scripts\activate.bat
    python "server\\publish_on_electron_release_server.py" --channel="stable" --platform="windows_64"  --base-url="http://ottbld02:1337" --username="admin" --password="$(password)" --path="%CD%\\electron_ui\\dist"
  displayName: 'Upload build to Electron Release Server'

- template: templates\cleaning_env.yml