{
 "title": "Cluster Submissions",
 "time": { "from": "now/y", "to": "now/y" },
 "panels": [
  {
   "title": "Submission per day by job type",
   "type": "graph",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"aedt_hpc_launcher\" WHERE $timeFilter GROUP BY time(1d),  \"job_type\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total submissions",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"aedt_hpc_launcher\" WHERE $timeFilter GROUP BY  \"cluster\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Submission log",
   "type": "table",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"count\" FROM \"autogen\".\"aedt_hpc_launcher\" WHERE $timeFilter GROUP BY  \"username\", \"job_type\", \"cluster\", \"version\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Job Type",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"aedt_hpc_launcher\" WHERE $timeFilter GROUP BY  \"job_type\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "User submissions",
   "type": "table",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 26 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"aedt_hpc_launcher\" GROUP BY  \"username\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}